### ISSUE TITLE
Lesson on using containers to encapsulate research environments

### ISSUE THREAD

**Issue by nuest** [AuthorCarpentry/authorcarpentry.github.io#3]
Replying to a deleted issue on the old repo:

> Hi, thanks for writing. We're in the process of rebooting AuthorCarpentry under a new organization on Github at https://github.com/AuthorCarpentry. Can you subscribe to that? We are planning on creating a lesson development repository under that organization. Would you like an invite?
>
> Thanks, Robert

Sure, I'd welcome an invite if you think the proposed lesson would be useful to your activities!

**Comment by tmorrell** [comment]
I've added you to our lesson-development repo.  We're still figuring out how we're organizing content, but feel free to add materials you think might be interesting there.
